### PR TITLE
fix aliucord

### PR DESCRIPTION
**Pull request by x6r**
please

### CODE REVIEW

**Comment by X1nto** [comment]
Man I wish I had enough courage to merge this PR

**Review by ItzOnlyAnimal — APPROVED** [review]
merge when @X1nto

**Comment by X1nto** [comment]
> merge when @X1nto

Soontm

**Review by mantikafasi — APPROVED** [review]

**Review by Vendicated — APPROVED** [review]
LGTM

**Review by amsyarasyiq — APPROVED** [review]

**Review by MeguminSama — APPROVED** [review]

**Comment by MeguminSama** [comment]
LGTM

**Review by AAGaming00 — APPROVED** [review]
LGTM

**Comment by ItzOnlyAnimal** [comment]
> **X1nto** locked as **too heated** and limited conversation to collaborators

**Comment by wingio** [comment]
<:4ktroll:843188323577102367>

**Review by wingio — APPROVED** [review]

**Review by lexisother — APPROVED** [review]
LGTM

**Review by thgeraads — APPROVED** [review]
LGTM

**Comment by ShiroBlank** [comment]
LGTM

**Review by veechiecooqu — APPROVED** [review]
why does not github app let you review commits

**Review by Cr3atable — APPROVED** [review]
i approve

**Review by yellowsink — APPROVED** [review]
i approb

**Review by phorcys420 — APPROVED** [review]
so true

**Review by phorcys420 — APPROVED** [review]
i approb 2

**Review by MoltenCoreDev — APPROVED** [review]
LGTM

**Comment by E-boi** [comment]
Great work sip!

**Review by phorcys420 — APPROVED** [review]
i approb 3

**Review by g1ZN7e9G — APPROVED** [review]
im just farming activity lol

**Review by phorcys420 — APPROVED** [review]
really cool

**Review by phorcys420 — APPROVED** [review]
so nice

**Review by phorcys420 — APPROVED** [review]
thank for very good contribution to foss commonity

**Review by g1ZN7e9G — APPROVED** [review]
wait uh are we reviewing reviews rn

**Review by phorcys420 — APPROVED** [review]
why ar my aprov not sending @evreyone help me

**Review by MoltenCoreDev — APPROVED** [review]
looks good to me

**Comment by yellowsink** [comment]
inb4 @phorcys420 ban for spam

**Review by phorcys420 — APPROVED** [review]
i fink my aprove sent hihihih x) i think i flod a litel bit
anyway very good push request

**Comment by MoltenCoreDev** [comment]
grubhub no ban pls

**Comment by phorcys420** [comment]
get wifi anywhere you went

**Comment by phorcys420** [comment]
@grubnugub /unsucrbribe from repo please is spam my emeil

**Comment by phorcys420** [comment]
image
stop omg !!! sis spaler

**Comment by MoltenCoreDev** [comment]
hello can i get a pizza

**Comment by phorcys420** [comment]
is not uber eat(s) you piece os shit

**Comment by MoltenCoreDev** [comment]
is this grubhub?

**Review by E-boi — APPROVED** [review]
Approve I do

**Review by g1ZN7e9G — CHANGES_REQUESTED** [review]
send a pizza

**Review by g1ZN7e9G — CHANGES_REQUESTED** [review]
68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3931363035373630313131303834333436322e706e67

**Comment by GangsterFox** [comment]
I approve

**Review by GangsterFox — APPROVED** [review]

**Comment by X1nto** [comment]
L

**Pull request merged**
